include ${GNUSTEP_MAKEFILES}/common.make

APP_NAME=Fraction
Fraction_HEADERS = Evaluator.h PMIEvaluator.h ChiSquaredEvaluator.h DatasetCollector.h
Fraction_OBJC_FILES = main.m Evaluator.m PMIEvaluator.m ChiSquaredEvaluator.m DatasetCollector.m


include ${GNUSTEP_MAKEFILES}/application.make
